language: python

python:
    - "3.7"


before_install:
    - cd _ML

install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source "$HOME/miniconda/etc/profile.d/conda.sh"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -n Hexnet_CPU python=$TRAVIS_PYTHON_VERSION -c conda-forge --file requirements_CPU_conda.txt
    - conda activate Hexnet_CPU
    - pip install -r requirements_CPU_pip.txt


script:
    - ./Hexnet.py --dataset


